title: Swift Evolution List
email: muiz.idn@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Yuhuu!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pondok-programmer.github.io/swift-evolution-jekyll/" # the base hostname & protocol for your site, e.g. http://example.com
theme: just-the-docs
exclude: [Submodules]
plugins:
  - jekyll-feed
aux_links:
    "Swift Evolution List":
      - "//github.com/pondok-programmer/swift-evolution-jekyll"